name: Publish Python distribution to PyPI and TestPyPI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*-*'
  pull_request:
    branches: [ master ]

jobs:
  lua-windows-build:
    name: Build lua for windows
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: sudo apt-get install --no-install-recommends -y gcc-mingw-w64 mingw-w64-i686-dev mingw-w64-x86-64-dev build-essential

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build LUA for windows i686
        run: cd lua && ./download-lua.sh && ./build-mingw-i686.sh

      - name: Build LUA for windows x86_64
        run: cd lua && ./download-lua.sh && ./build-mingw-x86_64.sh

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: lua-windows
          path: lua/lua-*.exe

  package-build:
    needs:
    - lua-windows-build
    name: Build python distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install build dependencies
      run: python -m pip install --upgrade pip build

    - name: Build package
      run: python -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    if: ${{ startsWith(github.event.ref, 'refs/tags/v') }}
    needs:
    - package-build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/Python-Lua-Helper

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
