name: Publish Python distribution to PyPI and TestPyPI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*-*'
  pull_request:
    branches: [ master ]

jobs:
  package-build:
    name: Build python distribution
    strategy:
      matrix:
        arch: [x86_64, x86, aarch64, armv7]
    runs-on: ubuntu-latest

    steps:
    - name: Setup alpine chroot for ${{ matrix.arch }}
      uses: jirutka/setup-alpine@v1
      with:
        branch: edge
        arch: ${{ matrix.arch }}
        packages: >
          build-base
          curl
          bash
          python3

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install build dependencies
      run: python -m pip install --upgrade pip build
      shell: alpine.sh {0}

    - name: Build package
      run: python -m build
      shell: alpine.sh {0}

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: package-linux-${{ matrix.arch }}
        path: dist/

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    if: ${{ startsWith(github.event.ref, 'refs/tags/v') }}
    needs:
    - package-build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/Python-Lua-Helper

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: package-*
        path: dist/

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
